[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "graphy-simple-visualizer"
version = "0.1"

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false